Repository tigrisdata/tigris, pull requests merged in 2022-12, with the labels that each got.

#658 fix: calculate db and collection tags only once for streaming requests
  server/metrics/measurement.go
  server/middleware/measure.go
Labels: medium

#667 fix: Update metrics tags from db to project
  api/server/v1/api.go
  server/config/options.go
  server/metrics/fdb.go
  server/metrics/measurement.go
  server/metrics/network.go
  server/metrics/requests.go
  server/metrics/search.go
  server/metrics/session.go
  server/metrics/size.go
  server/metrics/tags.go
  server/metrics/tags_test.go
  server/middleware/measure.go
  server/request/request.go
Labels: large

#670 Log panics, do not return to the user
  server/middleware/middleware.go
Labels: small

#673 feat: Support for default value attribute for fields
  go.mod
  go.sum
  internal/data.go
  schema/collection.go
  schema/collection_test.go
  schema/default.go
  schema/fields.go
  schema/schema.go
  schema/schema_test.go
  server/services/v1/conversion.go
  server/services/v1/mutator.go
  server/services/v1/mutator_test.go
  server/services/v1/query_runner.go
  test/v1/server/document_test.go
Labels: large

#674 Deduplicate schema constants
  schema/inference.go
  schema/inference_test.go
  test/v1/server/document_test.go
Labels: medium

#678 Improve local development setup
  .gitconfig/hooks/commit-msg
  Makefile
  schema/fields.go
  schema/fields_test.go
  schema/schema.go
  scripts/install_build_deps.sh
Labels: large

#679 feat: Cache as one of the Tigris store
  go.mod
  go.sum
  internal/cache.go
  internal/data.go
  internal/data.proto
  server/config/config.go
  server/config/options.go
  server/metadata/key_encoder.go
  store/cache/cache.go
  store/cache/cache_test.go
  store/cache/errors.go
  store/cache/store.go
  store/cache/stream.go
  store/cache/stream_test.go
  test/docker/docker-compose.yml
Labels: large

#683 Fix CLI tests
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/scaffold.sh
  test/v1/cli/tests.sh
Labels: large

#685 Fix Java schema
  schema/lang/java_test.go
  templates/schema/java/object.gotmpl
  test/v1/server/collection_test.go
  test/v1/server/database_test.go
Labels: small

#686 Fix error messages
  util/log/log.go
Labels: small

#687 Fix post commit error message
  server/services/v1/database/sessions.go
Labels: small

#688 fix: remove specific error values from unknown error sources
  server/metrics/measurement.go
  server/metrics/tags.go
  server/metrics/tags_test.go
  server/middleware/auth.go
  server/middleware/measure.go
  server/services/v1/database/sessions.go
  store/kv/kv.go
  store/search/ts.go
Labels: medium

#690 fix: local image failing to start sporadically
  docker/Dockerfile.local
  docker/service-local.sh
Labels: medium

#691 beta release
  docker/Dockerfile.local
  docker/service-local.sh
Labels: medium

#692 feat: Realtime HTTP APIs
  docker/service-local.sh
  server/config/options.go
  server/main.go
  server/muxer/http.go
  server/muxer/muxer.go
  server/services/v1/realtime.go
  server/services/v1/realtime/runner.go
  server/services/v1/realtime/sessions.go
  server/services/v1/realtime/types.go
  test/docker/docker-compose.yml
Labels: large

#693 feat: Adding a few realtime HTTP Middlewares
  api/server/v1/realtime.go
  server/middleware/http.go
  server/muxer/http.go
  server/request/request.go
Labels: large

#694 feat: Basic integration tests for realtime HTTP APIs
  api/server/v1/realtime.go
  server/main.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/services/v1/realtime/factory.go
  server/services/v1/realtime/factory_test.go
  server/services/v1/realtime/sessions.go
  test/config/config.go
  test/docker/docker-compose.yml
  test/v1/server/integration_test.go
  test/v1/server/realtime_test.go
Labels: large

#663 feat: database branching implementation
  api/server/v1/marshaler.go
  server/metadata/database.go
  server/metadata/database_test.go
  server/metadata/errors.go
  server/metadata/key_encoder_test.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/quota/quota_test.go
  server/quota/storage.go
  server/quota/storage_test.go
  server/services/v1/api.go
  server/services/v1/database/errors.go
  server/services/v1/database/query_runner.go
  server/services/v1/management.go
  server/services/v1/realtime/device_session.go
  server/services/v1/realtime/runner.go
Labels: large
