Repository tigrisdata/tigris, pull requests merged in 2023-02, with the labels that each got.

#766 Fix lint of TS schema
  schema/lang/typescript_test.go
  server/metadata/namespaces.go
  templates/schema/typescript/object.gotmpl
  test/v1/server/schema_test.go
Labels: small

#767 fix: Support query for nulls and non-indexed fields
  query/filter/filter.go
  query/filter/logical.go
  query/filter/selector.go
  server/services/v1/database/query_runner.go
  test/v1/server/document_test.go
  value/value.go
Labels: large

#768 Beta Release
  query/filter/filter.go
  query/filter/logical.go
  query/filter/selector.go
  schema/lang/typescript_test.go
  server/metadata/namespaces.go
  server/services/v1/database/query_runner.go
  templates/schema/typescript/object.gotmpl
  test/v1/server/document_test.go
  test/v1/server/schema_test.go
  value/value.go
Labels: large

#769 fix: bump up default max candidates limit to 100
  store/search/ts.go
Labels: small

#772 fix: Check on index, not on search field type
  server/services/v1/database/query_runner.go
Labels: small

#773 Release beta
  server/services/v1/database/query_runner.go
Labels: small

#774 refactor: Updated schema of custom claims in JWT
  server/middleware/auth.go
Labels: small

#775 fix: move getCollection from tenant to db
  server/metadata/key_encoder_test.go
  server/metadata/tenant.go
  server/services/v1/database/search_indexer.go
Labels: medium

#776 Beta release
  server/metadata/key_encoder_test.go
  server/metadata/tenant.go
  server/middleware/auth.go
  server/services/v1/database/search_indexer.go
Labels: medium

#777 fix: Change internal fields to _tigris prefix
  schema/collection.go
  schema/reserved.go
  schema/reserved_test.go
  schema/search.go
  schema/search_test.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  test/v1/server/document_test.go
Labels: large

#778 Upgrade Typesense to 0.24.0
  test/docker/docker-compose.yml
Labels: small

#790 Bump up ts to 0.24
  scripts/install_local_docker_deps.sh
Labels: small

#791 fix: Remove keys from search if update operation is for an object
  query/update/operator.go
  query/update/operator_test.go
  server/middleware/auth.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  test/v1/server/document_test.go
Labels: large

#792 Update tag line and fix links
  README.md
Labels: medium

#793 fix: Query using empty string quotes
  query/filter/selector.go
  value/value.go
Labels: small

#800 Release Beta
  README.md
  query/filter/selector.go
  query/update/operator.go
  query/update/operator_test.go
  schema/collection.go
  schema/reserved.go
  schema/reserved_test.go
  schema/search.go
  schema/search_test.go
  scripts/install_local_docker_deps.sh
  server/middleware/auth.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
  value/value.go
Labels: large

#802 chore: Break down query runner into multiple files
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/import_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_factory.go
  server/services/v1/database/search_runner.go
Labels: large

#799 feat: Add KV Atomic Add/Read/ReadRange
  server/transaction/manager.go
  store/kv/base.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/kv_test.go
  store/kv/noop_store.go
Labels: large

#798 fix: Added branch tag for metrics
  api/server/v1/api.go
  server/metrics/fdb.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/metrics_test.go
  server/metrics/network.go
  server/metrics/requests.go
  server/metrics/session.go
  server/metrics/size.go
  server/metrics/size_test.go
  server/metrics/tags.go
  server/metrics/tags_test.go
  server/middleware/measure.go
  server/quota/storage.go
  server/request/request.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/query_runner.go
Labels: debug image, large

#801 feat: Allow to query branch specific metrics
  server/metrics/datadog.go
  server/metrics/datadog_test.go
Labels: small

#805 Separate logs dump on tests failure into own step
  .github/workflows/go-test.yaml
  scripts/install_go.sh
Labels: small, medium

#734 Gather integration tests coverage
  .github/workflows/cli-test.yaml
  .github/workflows/go-test.yaml
  Makefile
  api/server/v1/marshaler.go
  docker/Dockerfile
  server/main.go
  store/kv/base.go
  store/kv/fdb.go
  test/docker/docker-compose.yml
  test/v1/client/client_test.go
  util/log/log.go
  util/util.go
Labels: large

#810 Explicitly enable main branch in tests to publish coverage
  .github/workflows/cli-test.yaml
  .github/workflows/go-test.yaml
Labels: small

#825 feat: GET /branches to return list of database branches
  api/server/v1/marshaler.go
  server/services/v1/api.go
  server/services/v1/database/database_runner.go
Labels: medium

#824 fix: Honor skip option for the read queries
  server/services/v1/database/query_runner.go
  test/v1/server/document_test.go
Labels: small, medium

#827 Proper unmarshal search index request
  api/server/v1/search.go
Labels: medium

#840 Fix handling non existing metadata
  server/metadata/namespace.go
  server/metadata/namespace_test.go
  server/metadata/user_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/namespace_metadata_provider.go
  server/services/v1/user_metadata_provider.go
Labels: small, medium

#841 chore: Fix make local_test
  server/metadata/namespace.go
  test/docker/docker-compose.yml
Labels: small

#842 fix: Handle floating point greater than 32 bit properly
  api/server/v1/validator.go
  query/filter/selector.go
  schema/fields_test.go
  server/middleware/measure.go
  server/services/v1/database/errors.go
  server/services/v1/database/query_runner.go
  store/search/ts.go
  value/value.go
Labels: medium

#845 Beta release
  api/server/v1/search.go
  api/server/v1/validator.go
  query/filter/selector.go
  schema/fields_test.go
  server/metadata/namespace.go
  server/metadata/namespace_test.go
  server/metadata/user_test.go
  server/middleware/auth.go
  server/middleware/measure.go
  server/request/request.go
  server/request/request_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/database/errors.go
  server/services/v1/database/query_runner.go
  server/services/v1/namespace_metadata_provider.go
  server/services/v1/user_metadata_provider.go
  store/search/ts.go
  test/docker/docker-compose.yml
  value/value.go
Labels: large

#846 fix: Switched to RawStdEncoding base64 decoding
  server/request/request.go
Labels: debug image, small

#847 Beta release
  server/request/request.go
Labels: small

#848 fix: To read namespace also support backward schema for metrics
  server/request/request.go
  server/request/request_test.go
Labels: debug image, small

#849 Beta release
  server/request/request.go
  server/request/request_test.go
Labels: small

#844 feat: Allow more fields attributes
  schema/fields.go
  schema/fields_test.go
  store/search/ts.go
  test/v1/server/document_test.go
Labels: small

#850 Release Beta
  schema/fields.go
  schema/fields_test.go
  store/search/ts.go
  test/v1/server/document_test.go
Labels: small

#843 feat: Support setting sort/facet on search index
  query/filter/logical_test.go
  query/search/search_test.go
  schema/collection.go
  schema/fields.go
  schema/rules_test.go
  schema/search.go
  server/metadata/tenant.go
  server/services/v1/database/query_runner_test.go
  server/services/v1/database/search_indexer_test.go
  test/v1/server/search_test.go
Labels: large

#854 fix: Log error only if during restart index reloading schema fails
  schema/fields.go
  schema/rules.go
  schema/search.go
  server/metadata/tenant.go
Labels: small

#830 fixes for secondary indexes and integration tests
  internal/data.go
  schema/collection.go
  server/config/options.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
Labels: debug image, small, large

#859 fix: Increased the timeout of auth0 calls to 30s
  server/services/v1/auth/provider.go
Labels: debug image, small

#860 fix: Fix error handling, timeouts, not leaking FDB error codes, etc
  schema/fields.go
  server/middleware/timeout.go
  server/services/v1/database/errors.go
  server/services/v1/database/import_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/sessions.go
  server/services/v1/search/runner.go
  store/kv/errors.go
  store/kv/fdb.go
Labels: large

#861 Release Beta
  go.mod
  go.sum
  internal/data.go
  query/filter/logical_test.go
  query/search/search_test.go
  schema/collection.go
  schema/fields.go
  schema/rules.go
  schema/rules_test.go
  schema/search.go
  server/config/options.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/middleware/timeout.go
  server/services/v1/auth/provider.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/errors.go
  server/services/v1/database/import_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_test.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/database/sessions.go
  server/services/v1/search/runner.go
  store/kv/errors.go
  store/kv/fdb.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
  test/v1/server/search_test.go
Labels: large

#863 Return empty response on non-existent user metadata
  server/services/v1/namespace_metadata_provider.go
  server/services/v1/user_metadata_provider.go
Labels: small

#865 Fix duplicate types in generated schema
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
Labels: large

#877 fix: Change size and count in secondary indexes
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/transaction/manager.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/noop_store.go
Labels: large

#878 chore: make client test re-runnable
  test/v1/client/client_test.go
Labels: small

#882 Enable quota metrics by default
  server/metrics/metrics.go
Labels: small

#884 Fix crash on non string id in the document
  server/services/v1/search/runner.go
  test/v1/server/search_test.go
Labels: small
