Repository tigrisdata/tigris, pull requests merged in 2023-06, with the labels that each got.

#1249 refactor: Do not increment metadata version if no changes in index schema
  server/metadata/tenant.go
  server/services/v1/search/session.go
Labels: small

#1250 Release Beta
  server/metadata/tenant.go
  server/services/v1/database/search_runner.go
  server/services/v1/search/session.go
  test/v1/server/server_test.go
Labels: small

#1251 fix: Break up tenants reloading on independent transactions
  server/metadata/tenant.go
  server/services/v1/api.go
Labels: medium

#1252 Release Beta
  server/metadata/tenant.go
  server/services/v1/api.go
Labels: medium

#1253 fix: Reduce log noise
  server/services/v1/auth/gotrue.go
Labels: small

#1241 refactor: refactor metronome metrics with consistent tags
  server/config/options.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/metronome.go
  server/metrics/metronome_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
Labels: debug image, large

#1256 chore: Disable depguard, nakedret and fix tagalign linters
  .golangci.yaml
  cmd/consistency/workload/document.go
  server/config/options.go
  server/services/v1/auth/gotrue.go
  server/services/v1/database/query_runner.go
  util/log/log.go
Labels: large

#1257 fix: Disable arm64 build
  .github/workflows/push-docker-arm64.yaml
Labels: small

#1258 Beta release
  .github/workflows/push-docker-arm64.yaml
  .golangci.yaml
  cmd/consistency/workload/document.go
  server/config/options.go
  server/services/v1/auth/gotrue.go
  server/services/v1/database/query_runner.go
  util/log/log.go
Labels: large

#1259 fix: enabling metronome and usage reporting by default
  server/config/options.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/provider_test.go
  server/services/v1/billing/reporter.go
Labels: medium

#1245 feat: build debug images with symbols enabled for releases and ad-hoc
  .github/workflows/push-docker-debug.yaml
  .github/workflows/push-docker-image.yaml
  Makefile
  docker/Dockerfile
  docker/Dockerfile.base
  scripts/install_delve.sh
  test/v1/server/document_test.go
Labels: debug image, medium, large

#1261 fix: Do not reload metadata on search delete index API
  server/config/options.go
  server/services/v1/search.go
  server/services/v1/search/session.go
Labels: small

#1262 Beta release
  .github/workflows/push-docker-debug.yaml
  .github/workflows/push-docker-image.yaml
  Makefile
  docker/Dockerfile
  docker/Dockerfile.base
  scripts/install_delve.sh
  server/config/options.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/provider_test.go
  server/services/v1/billing/reporter.go
  server/services/v1/search.go
  server/services/v1/search/session.go
  test/v1/server/document_test.go
Labels: large

#1247 feat: Support single node instance persistance and authentication
  .github/workflows/test-docker-local-image.yaml
  Makefile
  docker/Dockerfile
  docker/Dockerfile.local
  docker/service-local.sh
  scripts/install_local_docker_deps.sh
  scripts/service-local.sh
  scripts/test_docker_local.sh
  server/config/options.go
  server/main.go
  server/middleware/auth.go
  server/middleware/authz.go
  server/middleware/namespace.go
  server/muxer/grpc.go
  server/muxer/http.go
  server/muxer/muxer.go
  server/request/request.go
  server/services/v1/auth/common.go
  server/services/v1/auth/gotrue.go
  server/services/v1/database/database_runner.go
  store/kv/fdb.go
  test/config/config.go
  test/config/keys/test-token-A-hs.jwt
  test/config/keys/test-token-B-hs.jwt
  test/config/keys/test-token-hs.jwt
  test/config/keys/test-token-rsa-admin.jwt
  test/config/keys/test-token-rsa-editor.jwt
  test/config/keys/test-token-rsa-owner.jwt
  test/config/keys/test-token-rsa-readonly.jwt
  test/config/keys/test-token-rsa.jwt
  test/config/keys/test_ca.crt
  test/config/server.dev.yaml
  test/config/server.test.yaml
  test/config/server.test2.yaml
  test/docker/docker-compose.yml
  test/v1/cli/main.sh
  test/v1/server/auth_test.go
  test/v1/server/management_test.go
  test/v1/server/unix_test.go
  util/util.go
Labels: large

#1266 feat: Put user invitation methods behind config
  server/config/options.go
  server/services/v1/auth/user_manager.go
Labels: small

#1263 Beta release
  .github/workflows/test-docker-local-image.yaml
  Makefile
  docker/Dockerfile
  docker/Dockerfile.local
  docker/service-local.sh
  scripts/install_local_docker_deps.sh
  scripts/service-local.sh
  scripts/test_docker_local.sh
  server/config/options.go
  server/main.go
  server/middleware/auth.go
  server/middleware/authz.go
  server/middleware/namespace.go
  server/muxer/grpc.go
  server/muxer/http.go
  server/muxer/muxer.go
  server/request/request.go
  server/services/v1/auth/common.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/user_manager.go
  server/services/v1/database/database_runner.go
  store/kv/fdb.go
  test/config/config.go
  test/config/keys/test-token-A-hs.jwt
  test/config/keys/test-token-B-hs.jwt
  test/config/keys/test-token-hs.jwt
  test/config/keys/test-token-rsa-admin.jwt
  test/config/keys/test-token-rsa-editor.jwt
  test/config/keys/test-token-rsa-owner.jwt
  test/config/keys/test-token-rsa-readonly.jwt
  test/config/keys/test-token-rsa.jwt
  test/config/keys/test_ca.crt
  test/config/server.dev.yaml
  test/config/server.test.yaml
  test/config/server.test2.yaml
  test/docker/docker-compose.yml
  test/v1/cli/main.sh
  test/v1/server/auth_test.go
  test/v1/server/management_test.go
  test/v1/server/unix_test.go
  util/util.go
Labels: large

#1265 Fix peer credentials call on Darwin
  server/muxer/grpc.go
  server/muxer/http.go
  test/v1/server/unix_test.go
  util/util.go
  util/util_darwin.go
  util/util_linux.go
Labels: large

#1267 Beta release
  server/muxer/grpc.go
  server/muxer/http.go
  test/v1/server/unix_test.go
  util/util.go
  util/util_darwin.go
  util/util_linux.go
Labels: large

#1198 feat: Associate role with appkeys
  server/middleware/authz.go
  server/middleware/authz_test.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/gotrue_test.go
  server/services/v1/auth/user_manager.go
  test/v1/server/auth_test.go
Labels: medium, large

#1268 Beta release
  server/middleware/authz.go
  server/middleware/authz_test.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/gotrue_test.go
  server/services/v1/auth/user_manager.go
  test/v1/server/auth_test.go
Labels: large

#1270 fix: Skip reloading certain search indices
  server/config/options.go
  server/metadata/tenant.go
Labels: small

#1272 Revert "fix: Skip reloading certain search indices (#1270)"
  server/config/options.go
  server/metadata/tenant.go
Labels: small

#1273 Revert "Revert "fix: Skip reloading certain search indices (#1270)"
  server/config/options.go
  server/metadata/tenant.go
Labels: small

#1271 Beta release
  server/config/options.go
  server/metadata/tenant.go
Labels: small

#1275 Release Beta
  server/metadata/tenant.go
Labels: small

#1280 feat: Adding custom token separators to search index
  schema/search.go
  server/metadata/tenant.go
Labels: medium

#1281 fix: UpdateProject operation to authz
  api/server/v1/tx.go
  server/middleware/authz.go
  server/middleware/authz_test.go
Labels: small

#1282 Beta release
  api/server/v1/tx.go
  schema/search.go
  server/config/options.go
  server/metadata/tenant.go
  server/middleware/authz.go
  server/middleware/authz_test.go
Labels: medium
