Repository tigrisdata/tigris, pull requests merged in 2023-04, with the labels that each got.

#995 fix: Code generator to honor the search attributes
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
  templates/schema/go/object.gotmpl
  templates/schema/typescript/object.gotmpl
  test/v1/server/schema_test.go
Labels: medium, large

#994 Add codecov badge
  .codecov.yml
  Makefile
  README.md
Labels: small

#996 Increase the coverage target
  .codecov.yml
Labels: small

#1000 Allow UUID as id type for search document
  schema/rules.go
Labels: small

#984 feat: Add indexing to endpoints
  api/server/v1/marshaler.go
  schema/fields.go
  server/services/v1/api.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_factory.go
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  test/v1/server/schema_test.go
  test/v1/server/secondary_index_test.go
Labels: large

#999 feat: APIs to push billing metrics to metronome
  go.mod
  go.sum
  lib/uuid/uuid.go
  server/config/options.go
  server/services/v1/billing/event.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/management.go
Labels: large

#1003 feat: Consult global cluster for namespace creation
  server/config/options.go
  server/services/v1/database/sessions.go
Labels: large

#1004 feat: initial implementation of search tracking in global status
  server/metrics/global_status.go
  server/metrics/global_status_test.go
  server/metrics/measurement.go
  server/metrics/requests.go
  server/services/v1/billing/event.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/database/search_runner.go
  server/services/v1/management.go
  server/services/v1/search/runner.go
  store/search/measure.go
  store/search/search.go
  store/search/ts.go
Labels: large

#1001 feat: Order secondary indexes via field type
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  schema/fields.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  test/v1/server/secondary_index_test.go
  value/secondary_value_order.go
  value/value.go
  value/value_test.go
Labels: large

#1008 Fix panic in GetDatabaseBranches
  .github/workflows/test-docker-local-image.yaml
  Makefile
  server/metadata/tenant.go
  server/metadata/tenant_test.go
Labels: small

#1009 fix: Bump up search client with highlight object
  go.mod
  go.sum
  server/search/hits.go
Labels: small

#1010 fix: For array of date-time, convert it to string array for search instead of integer array
  schema/fields.go
  schema/queryable_test.go
Labels: small

#1011 Release Beta
  .github/workflows/test-docker-local-image.yaml
  Makefile
  go.mod
  go.sum
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  schema/fields.go
  schema/queryable_test.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/search/hits.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  test/v1/server/secondary_index_test.go
  value/secondary_value_order.go
  value/value.go
  value/value_test.go
Labels: large

#1014 feat: Support annotating user field as search id
  schema/fields.go
  schema/queryable.go
  schema/rules.go
  schema/rules_test.go
  schema/search.go
  schema/search_test.go
  server/services/v1/search/indexer.go
  server/services/v1/search/indexer_test.go
  server/services/v1/search/reader.go
  server/services/v1/search/runner.go
  test/v1/server/search_test.go
Labels: large

#1021 fix: Add small tool for search index, fix a bug with integer id(non document id field)
  cmd/consistency/consistency.go
  cmd/consistency/workload/document.go
  cmd/consistency/workload/queue.go
  cmd/consistency/workload/workload_ddl.go
  cmd/consistency/workload/workload_drop_create_write.go
  cmd/consistency/workload/workload_insert.go
  cmd/consistency/workload/workload_replace.go
  cmd/consistency/workload/workload_search.go
  cmd/consistency/workload/workload_small_load.go
  server/services/v1/database/errors.go
  server/services/v1/database/sessions.go
  server/services/v1/search/indexer.go
Labels: large

#1025 Use proto for document metadata encoding
  internal/cache.go
  internal/data.go
  internal/data_test.go
  server/services/v1/management.go
  store/kv/kv_test.go
Labels: large

#1030 feat: add metrics to secondary indexes
  server/config/options.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/secondary_index.go
  server/metrics/secondary_index_test.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
Labels: large

#1031 feat: Allow filtering for nested array of objects(one level) for standalone search index
  cmd/consistency/workload/document.go
  query/filter/filter.go
  schema/queryable.go
  schema/search.go
  test/v1/server/document_test.go
Labels: medium

#1013 feat: Usage reporter
  go.mod
  server/config/options.go
  server/main.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/metrics/global_status.go
  server/metrics/global_status_test.go
  server/quota/namespace.go
  server/services/v1/billing/event.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: large

#1033 Beta release
  go.mod
  server/config/options.go
  server/main.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/metrics/global_status.go
  server/metrics/global_status_test.go
  server/quota/namespace.go
  server/services/v1/billing/event.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: large

#1037 feat: Return matched token for nested fields in case of array of objects
  server/search/hits.go
  server/search/hits_test.go
Labels: large

#1039 chore: lint fixes
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/search/hits.go
  server/search/hits_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/reporter_test.go
Labels: medium

#1040 fix: logs for debugging reporter
  server/services/v1/billing/reporter.go
Labels: small

#1038 Release Beta
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/search/hits.go
  server/search/hits_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: large

#1041 fix: removing deadlock in tenant
  server/metadata/dictionary.go
  server/metadata/tenant.go
Labels: small

#1042 Beta release
  server/metadata/dictionary.go
  server/metadata/tenant.go
Labels: small

#1043 Respect configured log level
  config/server.dev.yaml
  config/server.test.yaml
  server/main.go
Labels: small

#1044 Update Go to 1.20.3
  scripts/install_go.sh
Labels: small

#1045 feat: Operational metrics for metronome integration
  server/metadata/tenant.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/metronome.go
  server/metrics/metronome_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/reporter.go
Labels: large

#1050 feat: Support $regex, $contains, $not in filters(extending hybrid search functionality)
  cmd/admin/main.go
  query/filter/comparison.go
  query/filter/comparison_test.go
  query/filter/filter.go
  query/filter/filter_test.go
  query/filter/key_builder.go
  query/filter/like.go
  query/filter/logical.go
  query/filter/selector.go
  test/v1/server/search_test.go
  value/collation.go
Labels: large

#1052 fix: Filtering with timestamp
  internal/data.go
  server/services/v1/billing/metronome.go
  server/services/v1/database/row_reader.go
  test/v1/server/secondary_index_test.go
Labels: medium

#1051 fix: Use empty collation if not set
  query/filter/comparison.go
  value/collation.go
Labels: small

#1055 fix: check metadata before reading collection metadata
  server/services/v1/api.go
Labels: small

#1061 Enable tests on merge_group event
  .github/workflows/cli-test.yaml
  .github/workflows/go-test.yaml
  .github/workflows/push-docker-image.yaml
  .github/workflows/push-docker-local-image.yaml
  .github/workflows/test-docker-local-image.yaml
Labels: small

#1063 refactor: Added additional logging to observe with ease
  server/services/v1/namespace_metadata_provider.go
  server/services/v1/user_metadata_provider.go
Labels: medium

#1057 feat: usage metrics only per tenant
  server/metrics/measurement.go
  server/metrics/requests.go
  server/middleware/measure.go
Labels: small

#1058 fix: Fixing metric tags and recording latency
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/reporter.go
Labels: small

#1064 Beta release
  .github/workflows/cli-test.yaml
  .github/workflows/go-test.yaml
  .github/workflows/push-docker-image.yaml
  .github/workflows/push-docker-local-image.yaml
  .github/workflows/test-docker-local-image.yaml
  cmd/admin/main.go
  internal/data.go
  query/filter/comparison.go
  query/filter/comparison_test.go
  query/filter/filter.go
  query/filter/filter_test.go
  query/filter/key_builder.go
  query/filter/like.go
  query/filter/logical.go
  query/filter/selector.go
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/metrics/requests.go
  server/middleware/measure.go
  server/services/v1/api.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/reporter.go
  server/services/v1/database/row_reader.go
  server/services/v1/namespace_metadata_provider.go
  server/services/v1/user_metadata_provider.go
  test/v1/server/search_test.go
  test/v1/server/secondary_index_test.go
  value/collation.go
Labels: large

#1065 refactor: Optimize by loading schemas for search only during the start of the server
  schema/queryable.go
  server/metadata/tenant.go
  server/metadata/tenant_tracker.go
  server/quota/quota_test.go
  server/quota/storage_test.go
  server/services/v1/api.go
  server/services/v1/realtime/device_session.go
Labels: large

#1067 fix: Disabled realtime test
  test/v1/server/realtime_test.go
Labels: small

#1070 Remove temporary fix for Go version in actions
  .github/workflows/cli-test.yaml
  .github/workflows/go-test.yaml
  Makefile
Labels: small

#1069 Collection statistics
  internal/data.go
  internal/data.proto
  internal/data_test.go
  server/config/options.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/metadata/version_test.go
  server/quota/quota_test.go
  server/quota/storage.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/management.go
  server/services/v1/observability.go
  server/transaction/manager.go
  store/kv/atomic.go
  store/kv/atomic_test.go
  store/kv/base.go
  store/kv/chunk_test.go
  store/kv/errors.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/kv_store.go
  store/kv/kv_test.go
  store/kv/measure.go
  store/kv/noop_store.go
  store/kv/stats.go
  store/kv/stats_test.go
  test/v1/server/collection_test.go
  test/v1/server/integration_test.go
Labels: large

#1076 Update CLI tests
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/main.sh
  test/v1/cli/search/import.sh
Labels: large

#1078 Fix crash in getting size statistics
  server/quota/storage.go
Labels: small

#1079 refactor: Added logging around app keys operations
  server/services/v1/auth/gotrue.go
Labels: medium

#1080 feat: Adding compression layer
  cmd/consistency/consistency.go
  cmd/consistency/workload/document.go
  cmd/consistency/workload/workload_compression.go
  internal/data.go
  internal/data.proto
  server/config/options.go
  store/kv/compression.go
  store/kv/compression_test.go
  store/kv/kv.go
Labels: large

#1081 feat: Add namespace name to the user invitation
  server/metadata/tenant.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/user_manager.go
  server/services/v1/service.go
  test/v1/server/auth_test.go
Labels: medium

#1084 fix: `recordTimerDuration` not started for metronome metrics
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/metrics/metronome_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
Labels: medium

#1085 refactor: Added logs on metrics query failures
  server/services/v1/observability.go
Labels: small

#1087 Beta release
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/metrics/metronome_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/observability.go
Labels: large

#1093 chore: configurable debug messages for all measurements
  server/config/options.go
  server/metrics/global_status.go
  server/middleware/measure.go
  store/kv/measure.go
Labels: large

#1092 fix: EQ KeyBuilder ignoring EQ fields
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  test/v1/server/secondary_index_test.go
Labels: small

#1094 chore: small secondary index metrics fixes
  server/metrics/measurement.go
  server/metrics/secondary_index.go
Labels: small

#1091 feat: Support sorting on primary key fields
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  schema/collection.go
  schema/queryable.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_planner.go
  server/services/v1/database/query_planner_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_test.go
  server/services/v1/database/row_reader.go
  server/services/v1/database/search_runner.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  test/v1/server/document_test.go
Labels: large

#1097 Release Beta
  cmd/admin/cmd/metadata.go
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  schema/collection.go
  schema/queryable.go
  server/config/options.go
  server/metadata/dictionary.go
  server/metadata/key_generator.go
  server/metadata/metadata.go
  server/metadata/queue.go
  server/metadata/schema.go
  server/metrics/global_status.go
  server/metrics/measurement.go
  server/metrics/secondary_index.go
  server/middleware/measure.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter_test.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_planner.go
  server/services/v1/database/query_planner_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_test.go
  server/services/v1/database/row_reader.go
  server/services/v1/database/search_runner.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/search/runner.go
  server/transaction/manager.go
  store/kv/base.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  store/kv/compression.go
  store/kv/compression_test.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/kv_store.go
  store/kv/kv_test.go
  store/kv/measure.go
  store/kv/noop_store.go
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
  test/v1/server/secondary_index_test.go
Labels: large

#1099 fix: remove dbg print
  server/services/v1/database/secondary_index_reader.go
Labels: small

#1102 fix: do not error on rm if mocks dont exist
  Makefile
Labels: small

#1103 Beta release
  .gitignore
  .mockery.yaml
  Makefile
  go.mod
  scripts/install_build_deps.sh
  scripts/install_test_deps.sh
  server/main.go
  server/metadata/mocks/NamespaceMetadataMgr.go
  server/metadata/tenant.go
  server/metrics/measurement.go
  server/services/v1/billing/event.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/mocks/Provider.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
  server/services/v1/billing_test.go
Labels: large

#1104 fix: For search index, move encoding/etc search errors on document level
  api/server/v1/search.go
  go.mod
  query/filter/key_builder.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/search/base_runner.go
  server/services/v1/search/errors.go
  server/services/v1/search/indexer.go
  server/services/v1/search/indexer_test.go
  server/services/v1/search/runner.go
  test/v1/server/search_test.go
Labels: large

#1105 fix: Disable metronome permanently for invalid namespace ids
  server/metadata/namespace.go
  server/services/v1/billing.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: large

#1110 Beta release
  schema/fields.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/tenant.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  test/v1/server/collection_test.go
  test/v1/server/secondary_index_test.go
Labels: large

#1111 fix: disable metronome reporting for default namespace
  server/services/v1/billing/reporter.go
Labels: debug image, small

#1026 Explicit schema versioning
  schema/collection.go
  schema/migration.go
  schema/schema.go
  schema/search.go
  server/metadata/database.go
  server/metadata/database_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/schema.go
  server/metadata/schema_test.go
  server/metadata/tenant.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/query_runner.go
  test/v1/server/schema_test.go
Labels: large

#1114 chore: remove full instrumentation for secondary index iterator
  server/services/v1/database/secondary_index_measure.go
Labels: small, medium

#1115 fix: Switch to project metric tag while querying metrics
  server/metrics/datadog.go
  server/metrics/datadog_test.go
Labels: small
