Repository tigrisdata/tigris, pull requests merged in 2023-01, with the labels that each got.

#695 fix: typesense failed to start in single image container sporadically
  docker/service-local.sh
Labels: small

#702 fix: Handling of conversion of str to int in case of wrong type
  server/services/v1/database/mutator.go
Labels: small

#698 feat: Realtime WS testing app
  cmd/realtime/app/app.go
  cmd/realtime/app/device.go
  cmd/realtime/main.go
  server/services/v1/realtime/device_session.go
  server/services/v1/realtime/serialization.go
Labels: large

#704 Test required fields validation
  schema/fields.go
  test/v1/server/document_test.go
Labels: medium

#697 feat: Add msgpack support to Realtime
  Makefile
  server/services/v1/realtime.go
  server/services/v1/realtime/channel_test.go
  server/services/v1/realtime/device_session.go
  server/services/v1/realtime/serialization.go
  test/docker/docker-compose.yml
Labels: large

#703 feat: Implemented cache API
  api/server/v1/cache.go
  go.mod
  server/metadata/database.go
  server/metadata/key_encoder.go
  server/metadata/key_encoder_test.go
  server/metadata/namespaces.go
  server/metadata/namespaces_test.go
  server/metadata/tenant.go
  server/request/request.go
  server/services/v1/api.go
  server/services/v1/cache.go
  server/services/v1/cache/request.go
  server/services/v1/cache/runner.go
  server/services/v1/cache/sessions.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/request.go
  server/services/v1/service.go
  store/cache/errors.go
  test/docker/docker-compose.yml
  test/v1/server/cache_test.go
Labels: large

#705 chore: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small

#709 chore: remove tigris_cache depends_on
  test/docker/docker-compose.yml
Labels: small

#708 Fix errors caught by lints
  .golangci.yaml
  api/server/v1/cache.go
  api/server/v1/marshaler.go
  cmd/consistency/workload/workload_ddl.go
  query/filter/key_builder.go
  schema/inference.go
  schema/inference_test.go
  schema/lang/java_test.go
  schema/lang/typescript_test.go
  schema/schema.go
  server/config/config.go
  server/metadata/tenant.go
  server/metrics/datadog.go
  server/quota/namespace_test.go
  server/quota/node_test.go
  server/quota/quota_test.go
  server/quota/storage_test.go
  server/request/request.go
  server/request/request_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/sessions.go
  server/transaction/manager.go
  test/v1/server/management_test.go
Labels: large

#710 fix: encoding information in stream data
  internal/cache.go
  internal/data.go
  internal/data.proto
  server/cdc/listener.go
  server/services/v1/realtime/channel_test.go
  server/services/v1/realtime/device_session.go
  server/services/v1/realtime/pusher.go
  server/services/v1/realtime/request.go
  server/services/v1/realtime/runner.go
  server/services/v1/realtime/serialization.go
  server/services/v1/realtime/types.go
  store/cache/stream_test.go
Labels: large

#712 Don't encode collection name on every request
  schema/collection.go
  server/metadata/tenant.go
  server/services/v1/database/query_runner.go
  test/v1/server/document_test.go
Labels: large

#714 fix: Remove language keywords restrictions
  api/server/v1/validator.go
  schema/fields.go
  schema/fields_test.go
  test/v1/server/collection_test.go
  test/v1/server/database_test.go
  util/util.go
Labels: medium

#716 refactor: cleanup topic type from collection at multiple places
  schema/collection.go
  schema/schema.go
  schema/schema_test.go
  server/services/v1/database/query_runner.go
Labels: medium

#713 Rt fixes
  server/services/v1/realtime.go
  server/services/v1/realtime/device_session.go
  server/services/v1/realtime/pusher.go
  server/services/v1/realtime/runner.go
  server/services/v1/realtime/serialization.go
Labels: medium

#718 fix: support mutating primary keys as part of Update request
  query/update/operator.go
  query/update/operator_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/realtime/pusher.go
  server/services/v1/realtime/serialization.go
  test/v1/server/document_test.go
Labels: large

#720 Fix Node version in release workflow
  .github/workflows/release.yaml
Labels: small

#722 refactor: Reduce allocation on heap and leverage stack by passing as value the Req/Resp objects
  server/services/v1/api.go
  server/services/v1/cache/request.go
  server/services/v1/cache/runner.go
  server/services/v1/cache/sessions.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/sessions.go
  server/services/v1/realtime/runner.go
  server/services/v1/realtime/sessions.go
Labels: large

#724 Fix local-image service-start script
  docker/service-local.sh
Labels: small

#725 Beta release
  docker/service-local.sh
  server/services/v1/api.go
  server/services/v1/cache/request.go
  server/services/v1/cache/runner.go
  server/services/v1/cache/sessions.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/sessions.go
  server/services/v1/realtime/runner.go
  server/services/v1/realtime/sessions.go
Labels: large

#726 Test local image
  .github/workflows/test-docker-local-image.yaml
  docker/service-local.sh
  test/v1/cli/tests.sh
Labels: medium

#727 refactor: Remove partition key reference from Collection
  schema/collection.go
  schema/fields.go
  schema/schema.go
  schema/schema_test.go
Labels: medium

#728 Fix CLI tests
  .github/workflows/cli-test.yaml
  test/v1/cli/main.sh
  test/v1/cli/scaffold.sh
Labels: large

#723 Stubs for arbitrary schema change added
  query/read/fields.go
  query/update/operator_test.go
  schema/collection.go
  schema/collection_test.go
  schema/migration.go
  schema/rules_test.go
  schema/schema_test.go
  server/metadata/schema.go
  server/metadata/schema_test.go
  server/metadata/tenant.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner.go
  test/v1/server/document_test.go
  test/v1/server/realtime_test.go
Labels: large

#732 Fix schema parsing
  .github/workflows/test-docker-local-image.yaml
  schema/fields.go
  schema/schema.go
  schema/schema_test.go
Labels: large

#731 fix: Support nullable for arrays and objects
  schema/collection.go
  schema/collection_test.go
  schema/reserved.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  test/v1/server/collection_test.go
  test/v1/server/database_test.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
Labels: large

#733 Release beta
  .github/workflows/cli-test.yaml
  .github/workflows/test-docker-local-image.yaml
  docker/service-local.sh
  query/read/fields.go
  query/update/operator_test.go
  schema/collection.go
  schema/collection_test.go
  schema/fields.go
  schema/migration.go
  schema/reserved.go
  schema/rules_test.go
  schema/schema.go
  schema/schema_test.go
  server/metadata/schema.go
  server/metadata/schema_test.go
  server/metadata/tenant.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  test/v1/cli/main.sh
  test/v1/cli/scaffold.sh
  test/v1/server/collection_test.go
  test/v1/server/database_test.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
  test/v1/server/realtime_test.go
Labels: large

#738 chore: Fixed error message to reflect 'project' from legacy errors
  server/metadata/errors.go
  server/services/v1/database/query_runner.go
  test/v1/cli/main.sh
  test/v1/server/database_test.go
  test/v1/server/document_test.go
Labels: medium

#739 chore: make fdb hard drop the default
  server/config/options.go
Labels: small

#741 fix: Allow null when format is int32/int64
  schema/collection.go
  schema/collection_test.go
Labels: small

#742 refactor: Refactoring search index and collection object
  query/update/operator_test.go
  schema/collection.go
  schema/collection_test.go
  schema/rules_test.go
  schema/schema_test.go
  schema/search.go
  schema/search_test.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_reader.go
  test/v1/server/collection_test.go
Labels: large

#744 docs: docstring for atomic update api
  query/update/operator.go
Labels: small

#746 fix: Get the branch name where custom unmarshaler are used
  api/server/v1/marshaler.go
  schema/collection.go
Labels: small

#749 docs: Fixed README broken links
  README.md
Labels: small

#750 Fix more links in README
  README.md
Labels: small

#748 Support incompatible schema changes
  query/update/operator_test.go
  schema/collection.go
  schema/collection_test.go
  schema/fields.go
  schema/migration.go
  schema/migration_test.go
  schema/rules.go
  schema/rules_test.go
  schema/schema.go
  schema/schema_test.go
  schema/search.go
  server/config/options.go
  server/metadata/tenant.go
  server/metrics/metrics.go
  server/metrics/metrics_test.go
  server/services/v1/cache/runner.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/sessions.go
  test/v1/server/cache_test.go
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
  test/v1/server/schema_test.go
Labels: large

#753 Use jsoniter consistently
  api/server/v1/cache.go
  api/server/v1/marshaler.go
  api/server/v1/marshaler_test.go
  api/server/v1/search.go
  cmd/consistency/workload/document.go
  lib/json/encoder.go
  query/update/operator_test.go
  schema/collection_test.go
  schema/inference.go
  schema/lang/schema.go
  schema/migration.go
  schema/migration_test.go
  schema/schema.go
  schema/search_test.go
  server/metadata/dictionary.go
  server/metadata/namespaces.go
  server/metadata/schema.go
  server/metadata/tenant.go
  server/search/facets_test.go
  server/search/sorted_hits_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/database/search_reader.go
  server/services/v1/management.go
  server/services/v1/realtime/errors.go
  server/services/v1/search/runner.go
  store/search/ts.go
  test/v1/client/driver_test.go
  test/v1/server/cache_test.go
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  test/v1/server/realtime_test.go
  test/v1/server/search_test.go
  test/v1/server/server_test.go
  util/util.go
Labels: large

#754 docs: Add RFC for secondary indexes
  docs/rfcs/001-secondary-indexes.md
Labels: large

#755 Generate decorators based TypeScript schema
  schema/default.go
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
  templates/schema/typescript/object.gotmpl
  templates/schema/typescript/objectj_original.gotmpl
  test/v1/server/collection_test.go
  test/v1/server/database_test.go
  test/v1/server/document_test.go
  test/v1/server/schema_test.go
  util/util.go
Labels: large

#757 fix: Add discord community
  README.md
Labels: small

#756 feat: Create collation wrapper for value
  query/filter/filter.go
  query/filter/selector.go
  server/services/v1/database/query_runner.go
  value/collation.go
  value/value.go
  value/value_test.go
Labels: large

#752 Build per field schema version lookup structure
  schema/collection.go
  schema/migration.go
  schema/migration_test.go
  schema/schema_test.go
Labels: medium, large

#758 Support defaults, maxLength, required tags in Golang generated …
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
  templates/schema/go/object.gotmpl
  test/v1/server/schema_test.go
Labels: large

#761 feat: Backward compatibility rules and checks for search indexes
  schema/migration.go
  schema/rules.go
  schema/rules_test.go
  schema/search.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/services/v1/search/runner.go
Labels: large

#763 Added cluster and collection metadata subspaces
  server/metadata/cluster.go
  server/metadata/cluster_test.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/metadata.go
  server/metadata/namespaces.go
  server/metadata/namespaces_test.go
  server/metadata/schema.go
  server/metadata/schema_test.go
  server/metadata/subscope_registry.go
  server/metadata/tenant.go
  server/metadata/users.go
  server/metadata/users_test.go
  server/services/v1/service.go
Labels: large

#764 Fix maxLength tags separator in Golang generated schema
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
  templates/schema/go/object.gotmpl
Labels: small

#765 Beta release
  schema/lang/go_test.go
  schema/lang/java_test.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript_test.go
  server/metadata/cluster.go
  server/metadata/cluster_test.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/metadata.go
  server/metadata/namespaces.go
  server/metadata/namespaces_test.go
  server/metadata/schema.go
  server/metadata/schema_test.go
  server/metadata/subscope_registry.go
  server/metadata/tenant.go
  server/metadata/users.go
  server/metadata/users_test.go
  server/services/v1/service.go
  templates/schema/go/object.gotmpl
Labels: large
