Repository tigrisdata/tigris, pull requests merged in 2023-05, with the labels that each got.

#1116 feat: log long method calls in the error log
  server/config/options.go
  server/metrics/measurement.go
Labels: medium

#1118 feat: log the number of documents for a slow call
  server/metadata/namespace.go
  server/metrics/global_status.go
  server/metrics/measurement.go
  server/middleware/measure.go
  store/kv/measure.go
  store/search/measure.go
Labels: small

#1113 feat: search index metrics
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/metrics/measurement.go
  server/metrics/measurement_test.go
  server/metrics/size.go
  server/quota/storage.go
Labels: large

#1119 Recurse into arrays to allow nullable fields
  schema/collection.go
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/main.sh
Labels: small

#1121 Allow user to explicitly specify fields as nullable
  schema/factory_builder.go
  schema/fields.go
  schema/fields_test.go
  schema/rules.go
  test/v1/server/collection_test.go
Labels: large

#1120 feat: Support filtering on complex types
  config/server.dev.yaml
  query/filter/comparison.go
  query/filter/comparison_test.go
  query/filter/filter.go
  query/filter/selector.go
  query/filter/selector_test.go
  schema/queryable.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
  value/eval.go
  value/value.go
Labels: large

#1122 Beta release
  config/server.dev.yaml
  query/filter/comparison.go
  query/filter/comparison_test.go
  query/filter/filter.go
  query/filter/selector.go
  query/filter/selector_test.go
  schema/collection.go
  schema/factory_builder.go
  schema/fields.go
  schema/fields_test.go
  schema/queryable.go
  schema/rules.go
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/metrics/global_status.go
  server/metrics/measurement.go
  server/metrics/measurement_test.go
  server/metrics/size.go
  server/middleware/measure.go
  server/quota/storage.go
  store/kv/measure.go
  store/search/measure.go
  test/docker/docker-compose.yml
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/main.sh
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  value/eval.go
  value/value.go
Labels: large

#1125 fix: Allow dashes in while querying metric tags
  server/services/v1/observability.go
  server/services/v1/observability_test.go
Labels: small

#1123 feat: Request Usage data from metronome
  server/config/options.go
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/services/v1/billing.go
  server/services/v1/billing/event.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter_test.go
  server/services/v1/billing_test.go
Labels: large

#1128 fix: Fixed metrics filtering for tigris_operation
  server/metrics/datadog.go
  server/metrics/datadog_test.go
Labels: small

#1127 feat: Add support for building(backfilling) collection search index using an API
  api/server/v1/tx.go
  cmd/consistency/workload/document.go
  server/middleware/timeout.go
  server/services/v1/api.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/provider.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/errors.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/query_runner_factory.go
  server/services/v1/database/request.go
  server/services/v1/database/sessions.go
  server/services/v1/database/stream_producer.go
  test/v1/server/document_test.go
Labels: large

#1130 feat: reporting search index sizes to metronome
  server/main.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: medium

#1132 fix: use search for single field sort
  config/server.dev.yaml
  server/config/options.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
  server/services/v1/database/query_runner.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
Labels: large

#1134 Better detection of unchanged schema
  schema/schema.go
  server/metadata/tenant.go
  server/services/v1/api.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/sessions.go
Labels: medium

#1140 Avoid allocation and copy in custom unmarshal
  api/server/v1/marshaler.go
Labels: small

#1141 Report server origin on start
  server/main.go
Labels: small

#1144 fix: Saving metadata on refresh accounts to cache
  server/metadata/tenant.go
Labels: small

#1145 fix: Fix schema validation for dot notation in Update Query
  server/services/v1/database/base_runner.go
  server/services/v1/database/mutator.go
  test/v1/server/document_test.go
Labels: large

#1146 Release beta
  server/metadata/tenant.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/mutator.go
  test/v1/server/document_test.go
Labels: large

#1147 fix: Remove extra null fields from search response
  server/config/options.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/search/indexer.go
  test/v1/server/document_test.go
  util/util.go
  util/util_test.go
Labels: large

#1148 Release Beta
  server/config/options.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/search/indexer.go
  test/v1/server/document_test.go
  util/util.go
  util/util_test.go
Labels: large

#1150 fix: Valid sort with no indexed fields in filter
  server/services/v1/database/base_runner.go
  test/v1/server/secondary_index_test.go
Labels: small

#1149 fix: Add new index building state
  schema/fields.go
  server/metadata/tenant.go
  server/services/v1/api.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/indexer_runner.go
Labels: medium

#1152 fix: Allow project/collection/branch name empty in query
  server/services/v1/observability.go
  server/services/v1/observability_test.go
Labels: small

#1153 Beta release
  schema/fields.go
  server/metadata/tenant.go
  server/metrics/measurement.go
  server/metrics/measurement_test.go
  server/metrics/network.go
  server/metrics/network_test.go
  server/middleware/measure.go
  server/services/v1/api.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/observability.go
  server/services/v1/observability_test.go
  test/v1/server/secondary_index_test.go
Labels: large

#1154 fix: Added more test to cover the invitation apis
  test/v1/server/auth_test.go
Labels: large

#1155 fix: Sanitize the metrics input to match what is ingested
  server/metadata/tenant.go
  server/metrics/datadog.go
  server/metrics/datadog_test.go
Labels: small

#1156 Beta release
  server/metadata/tenant.go
  server/metrics/datadog.go
  server/metrics/datadog_test.go
  test/v1/server/auth_test.go
Labels: large

#1137 feat: Background workers for index building
  api/server/v1/marshaler.go
  config/server.dev.yaml
  server/config/options.go
  server/main.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/queue.go
  server/metadata/queue_test.go
  server/metadata/tenant.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/workers/worker.go
  server/services/v1/workers/worker_test.go
  test/docker/docker-compose.yml
  test/v1/server/secondary_index_test.go
Labels: large

#1158 fix: Added more log to auth failures
  server/config/options.go
  server/middleware/auth.go
Labels: debug image, small

#1159 Beta release
  api/server/v1/marshaler.go
  config/server.dev.yaml
  query/update/operator.go
  query/update/operator_test.go
  server/config/options.go
  server/main.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/queue.go
  server/metadata/queue_test.go
  server/metadata/tenant.go
  server/middleware/auth.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/workers/worker.go
  server/services/v1/workers/worker_test.go
  test/docker/docker-compose.yml
  test/v1/server/document_test.go
  test/v1/server/secondary_index_test.go
Labels: large

#1160 fix: finish tracing once metrics are recorded
  server/services/v1/billing/metronome.go
Labels: debug image, small

#1161 fix: skip reporting 0 values to metronome
  server/services/v1/billing/event.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/metronome.go
Labels: medium

#1162 Beta release
  server/services/v1/billing/event.go
  server/services/v1/billing/event_test.go
  server/services/v1/billing/metronome.go
Labels: medium

#1163 fix: Update search query to look into accessibleNamespaces for user
  server/services/v1/auth/user_manager.go
Labels: small

#1164 Beta release
  server/services/v1/auth/user_manager.go
Labels: small

#1036 Remove generics from key builder
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  schema/collection.go
  schema/queryable.go
  schema/queryable_test.go
  schema/search.go
  server/services/v1/database/query_planner.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/database/secondary_index_reader.go
Labels: medium, large, SecondaryIndexes

#1167 fix: Handle filtering completely on Tigris layer for read queries, handle escaped characters and unicode properly
  query/filter/selector.go
  query/filter/selector_test.go
  query/search/search_test.go
  server/middleware/auth.go
  server/services/v1/database/query_runner.go
  test/v1/server/document_test.go
  value/value.go
Labels: large

#1168 Release Beta
  cmd/consistency/consistency.go
  cmd/consistency/workload/document.go
  cmd/consistency/workload/workload_compression.go
  config/server.dev.yaml
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  query/filter/selector.go
  query/filter/selector_test.go
  query/search/search_test.go
  schema/collection.go
  schema/queryable.go
  schema/queryable_test.go
  schema/search.go
  server/middleware/auth.go
  server/middleware/measure.go
  server/services/v1/database/query_planner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/database/secondary_index_reader.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  test/docker/docker-compose.yml
  test/v1/server/document.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
  value/value.go
Labels: large

#1169 fix: Fixed user search
  server/services/v1/auth/user_manager.go
Labels: debug image, small

#1170 Beta release
  server/services/v1/auth/user_manager.go
Labels: small

#1171 fix: Wrap properly kv stats error
  store/kv/stats.go
Labels: small

#1172 fix: Add queue metrics
  server/config/options.go
  server/metrics/metrics.go
  server/metrics/queue.go
  server/metrics/queue_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/workers/worker.go
Labels: large

#1176 feat: Return server response time in headers
  api/server/v1/header.go
  server/metrics/measurement.go
  server/middleware/headers.go
  server/middleware/measure.go
  server/middleware/middleware.go
  store/kv/chunk.go
Labels: medium

#1165 feat: Index metadata toggle and write mode index
  query/filter/key_builder_test.go
  schema/collection.go
  schema/fields.go
  schema/queryable.go
  schema/queryable_test.go
  schema/schema.go
  schema/schema_test.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/workers/worker.go
Labels: large, SecondaryIndexes

#1180 Release Beta
  api/server/v1/header.go
  query/filter/key_builder_test.go
  schema/collection.go
  schema/fields.go
  schema/queryable.go
  schema/queryable_test.go
  schema/schema.go
  schema/schema_test.go
  server/config/options.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/queue.go
  server/metrics/queue_test.go
  server/middleware/headers.go
  server/middleware/measure.go
  server/middleware/middleware.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/secondary_index_measure.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/workers/worker.go
  store/kv/chunk.go
Labels: large

#1181 feat: Add more server timing information in the header
  server/config/options.go
  server/metrics/measurement.go
  server/middleware/headers.go
  server/middleware/measure.go
  server/middleware/middleware.go
  server/services/v1/database/sessions.go
Labels: large

#1182 Release Beta
  server/config/options.go
  server/metrics/measurement.go
  server/middleware/headers.go
  server/middleware/measure.go
  server/middleware/middleware.go
  server/services/v1/database/sessions.go
Labels: large

#1183 feat: add error status to long requests
  server/metrics/measurement.go
  server/metrics/measurement_test.go
  server/middleware/measure.go
Labels: small

#1184 fix: Relax(allow nulls) schema validation for objects inside arrays
  schema/collection.go
  schema/collection_test.go
  server/services/v1/database/base_runner.go
Labels: small, large

#1185 Release Beta
  schema/collection.go
  schema/collection_test.go
  server/metrics/measurement.go
  server/metrics/measurement_test.go
  server/middleware/measure.go
  server/services/v1/database/base_runner.go
Labels: large

#1186 fix: Sanitize array of objects by removing nulls before sending to search
  server/services/v1/database/base_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
Labels: medium

#1187 Release Beta
  server/services/v1/database/base_runner.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_indexer_test.go
Labels: medium

#1189 feat: long request contains number of inserted documents
  server/services/v1/database/query_runner.go
Labels: small

#1190 fix: check metadata version before reads
  server/services/v1/api.go
Labels: small

#1191 refactor: Only use indexing store for sorting results
  query/filter/filter.go
  query/search/search.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_reader.go
  store/search/ts.go
Labels: medium

#1192 Release Beta
  go.mod
  go.sum
  query/filter/filter.go
  query/search/search.go
  server/config/options.go
  server/metrics/measurement.go
  server/services/v1/api.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_reader.go
  store/search/ts.go
Labels: large

#1195 fix: check for missing collection
  server/services/v1/workers/worker.go
Labels: small

#1196 Latest Beta
  server/metrics/measurement.go
  server/metrics/requests.go
  server/middleware/measure.go
  server/services/v1/workers/worker.go
Labels: medium

#1199 fix: Do not increment version on get index requests
  server/services/v1/search.go
  server/services/v1/search/session.go
Labels: medium

#1200 Release Beta
  server/services/v1/search.go
  server/services/v1/search/session.go
Labels: medium

#1179 feat: background search building
  api/server/v1/marshaler.go
  cmd/admin/main.go
  config/server.dev.yaml
  server/config/options.go
  server/main.go
  server/metadata/collection.go
  server/metadata/queue.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/indexer_runner.go
  server/services/v1/workers/worker.go
  server/services/v1/workers/worker_test.go
  store/search/measure.go
  store/search/search.go
  test/docker/docker-compose.yml
  test/v1/server/collection_test.go
  test/v1/server/document_test.go
  test/v1/server/search_test.go
Labels: large

#1202 fix: catch background worker panics
  server/services/v1/workers/worker.go
Labels: small

#1201 feat: Add log_only support to authorization
  config/server.test.yaml
  server/config/options.go
  server/middleware/auth.go
  server/middleware/authz.go
  server/middleware/authz_test.go
  server/types/types.go
Labels: debug image, large

#1209 fix: Fixed the error reset for log_only
  server/middleware/authz.go
Labels: debug image, small

#1210 Beta release
  config/server.test.yaml
  server/config/options.go
  server/middleware/auth.go
  server/middleware/authz.go
  server/middleware/authz_test.go
  server/types/types.go
Labels: large

#1208 fix: avoid saving copies for namespace accounts
  server/metadata/namespace.go
  server/metadata/tenant.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: debug image, small, medium

#1211 chore: Add configurable log for collection search filter
  server/config/options.go
  server/metadata/tenant.go
  server/services/v1/database/search_runner.go
Labels: small

#1214 fix: Count single write unit for each search deletes, minimum threshold for compression configurable, and fixing go imports
  config/server.dev.yaml
  config/server.test.yaml
  server/config/options.go
  server/metadata/key_generator.go
  server/metadata/metadata.go
  server/services/v1/billing_test.go
  server/services/v1/database/search_reader.go
  server/services/v1/search/base_runner.go
  server/services/v1/search/runner.go
  server/services/v1/search/session.go
  store/kv/compression.go
Labels: small, medium

#1216 Release Beta
  config/server.dev.yaml
  config/server.test.yaml
  server/config/options.go
  server/metadata/key_generator.go
  server/metadata/metadata.go
  server/metadata/tenant.go
  server/services/v1/billing_test.go
  server/services/v1/database/search_reader.go
  server/services/v1/database/search_runner.go
  server/services/v1/search/base_runner.go
  server/services/v1/search/runner.go
  server/services/v1/search/session.go
  store/kv/compression.go
Labels: medium

#1217 Beta release
  Makefile
  server/metadata/tenant.go
  server/metrics/measurement.go
  server/metrics/metronome.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
Labels: large

#1218 fix: Allow to disable search indexing
  api/server/v1/header.go
  server/request/request.go
  server/services/v1/database/search_indexer.go
Labels: small

#1221 fix: metronome nil check before using
  server/services/v1/billing.go
  server/services/v1/billing/reporter.go
Labels: debug image, small

#1219 Beta release
  api/server/v1/header.go
  server/request/request.go
  server/services/v1/billing.go
  server/services/v1/billing/reporter.go
  server/services/v1/database/search_indexer.go
Labels: small

#1222 fix: Marshaling JSON responses for billing APIs
  api/server/v1/marshaler.go
  api/server/v1/marshaler_test.go
Labels: large

#1224 chore: Add a log when builder not returning an error and keys are empty
  query/filter/key_builder.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
Labels: small

#1225 fix: Update authz for search methods
  api/server/v1/tx.go
  server/middleware/authz.go
  server/middleware/authz_test.go
Labels: large

#1226 fix: Moving namespace meta nil up a level
  server/services/v1/billing/reporter.go
Labels: small

#1227 Beta release
  api/server/v1/tx.go
  query/filter/key_builder.go
  server/middleware/authz.go
  server/middleware/authz_test.go
  server/services/v1/billing/reporter.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
Labels: large

#1228 Properly generate pointer types in language schema
  api/server/v1/tx.go
  query/filter/key_builder.go
  schema/fields.go
  schema/fields_test.go
  schema/inference.go
  schema/inference_test.go
  schema/lang/go_test.go
  schema/lang/java.go
  schema/lang/java_test.go
  schema/lang/multi_type.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript.go
  schema/lang/typescript_test.go
  server/config/options.go
  server/metadata/tenant.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
  templates/schema/go/object.gotmpl
  test/config/config.go
  test/v1/server/auth_test.go
Labels: large

#1229 fix: Fix search write units
  server/metrics/global_status.go
Labels: small

#1230 Release Beta
  api/server/v1/tx.go
  query/filter/key_builder.go
  schema/fields.go
  schema/fields_test.go
  schema/inference.go
  schema/inference_test.go
  schema/lang/go_test.go
  schema/lang/java.go
  schema/lang/java_test.go
  schema/lang/multi_type.go
  schema/lang/schema.go
  schema/lang/schema_test.go
  schema/lang/typescript.go
  schema/lang/typescript_test.go
  server/config/options.go
  server/metadata/tenant.go
  server/metrics/global_status.go
  server/services/v1/billing/reporter.go
  server/services/v1/billing/reporter_test.go
  templates/schema/go/object.gotmpl
  test/config/config.go
  test/v1/server/auth_test.go
Labels: large

#1231 fix: Update authz for billing + observability methods
  api/server/v1/tx.go
  server/middleware/authz.go
  server/middleware/authz_test.go
Labels: small

#1232 Beta release
  api/server/v1/tx.go
  server/middleware/authz.go
  server/middleware/authz_test.go
Labels: small

#1236 fix: Fixed auth test container configuration
  server/middleware/authz.go
  test/docker/docker-compose.yml
Labels: small

#1235 feat: search write metrics
  server/metrics/measurement.go
  server/metrics/requests.go
  server/quota/storage.go
Labels: small

#1238 Release Beta
  server/metrics/measurement.go
  server/metrics/requests.go
  server/middleware/authz.go
  server/quota/storage.go
  test/docker/docker-compose.yml
Labels: small

#1234 Upgrade dependencies
  go.mod
  go.sum
  scripts/install_go.sh
  scripts/install_test_deps.sh
Labels: large

#1239 fix: Do not reload metadata if nothing changed in describeCollection
  server/metadata/tenant.go
  server/services/v1/api.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/sessions.go
  server/transaction/manager.go
Labels: medium

#1240 Release Beta
  go.mod
  go.sum
  scripts/install_go.sh
  scripts/install_test_deps.sh
  server/metadata/tenant.go
  server/services/v1/api.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/sessions.go
  server/transaction/manager.go
Labels: large

#1243 fix: More accurate logging(non empty filters)
  server/services/v1/database/search_runner.go
Labels: small

#1248 fix: Fixed TestInfo test
  test/v1/server/server_test.go
Labels: small
