Repository tigrisdata/tigris, pull requests merged in 2023-03, with the labels that each got.

#829 feat: Secondary index reader
  internal/data.go
  query/filter/filter.go
  query/filter/key_builder.go
  query/filter/key_builder_test.go
  query/filter/selector.go
  schema/fields.go
  server/config/options.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/row_reader.go
  server/services/v1/database/secondary_index_reader.go
  test/docker/docker-compose.yml
  test/v1/server/secondary_index_test.go
  value/value.go
Labels: debug image, large

#892 fix: Add more validations for search schema
  schema/fields.go
  schema/search.go
  schema/search_test.go
  server/services/v1/search/runner.go
Labels: medium

#889 feat: Configure which fields to add to index
  config/server.dev.yaml
  query/filter/filter.go
  query/filter/logical.go
  query/filter/selector.go
  schema/collection.go
  schema/fields.go
  schema/fields_test.go
  schema/rules.go
  schema/rules_test.go
  schema/search.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/search_runner.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/search/runner.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
Labels: large

#896 chore: lower value on flaky size test
  schema/search_test.go
  server/services/v1/database/secondary_indexer_test.go
Labels: small

#880 feat: Tigris Gotrue integration
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/auth/common.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/provider.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/docker/test-token.jwt
  test/v1/server/auth_test.go
  test/v1/server/integration_test.go
  test/v1/server/server_test.go
Labels: large

#898 Beta release
  schema/search_test.go
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/auth/common.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/provider.go
  server/services/v1/database/secondary_indexer_test.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/docker/test-token.jwt
  test/v1/server/auth_test.go
  test/v1/server/integration_test.go
  test/v1/server/server_test.go
Labels: large

#900 feat: Bump grpc max receive message limit to 16MB
  server/muxer/grpc.go
Labels: small

#901 Release beta
  server/muxer/grpc.go
Labels: small

#890 Push to quay.io as well
  .github/workflows/push-docker-image.yaml
Labels: small, medium

#902 fix: only log unexpected errors in match
  query/filter/selector.go
Labels: debug image, small

#903 Beta release
  .github/workflows/push-docker-image.yaml
  query/filter/selector.go
Labels: small

#905 fix: Fixed the error status code in case of auth failure
  server/services/v1/auth/gotrue.go
  test/v1/server/auth_test.go
Labels: small

#906 Push tigris-debug to Quay.io as well
  .github/workflows/publish-debug-image.yaml
  .github/workflows/push-docker-image.yaml
Labels: debug image, small

#909 fix: List app keys by tigris project
  server/services/v1/auth/gotrue.go
  test/v1/server/auth_test.go
  test/v1/server/document_test.go
Labels: medium

#914 fix: Fixed the empty keys response
  api/server/v1/marshaler.go
  test/v1/server/auth_test.go
Labels: small

#915 fix: Fixed parsing of createdAt field from gotrue response
  server/services/v1/auth/gotrue.go
  test/v1/server/auth_test.go
Labels: small

#916 Beta release
  .github/workflows/publish-debug-image.yaml
  .github/workflows/push-docker-image.yaml
  api/server/v1/marshaler.go
  server/services/v1/auth/gotrue.go
  test/v1/server/auth_test.go
  test/v1/server/document_test.go
Labels: large

#917 Optionally disable schema validation
  api/server/v1/header.go
  query/filter/selector.go
  server/request/request.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  test/v1/server/schema_test.go
Labels: medium

#920 fix: Revert empty array response when app keys are empty for list call
  api/server/v1/marshaler.go
  test/v1/server/auth_test.go
Labels: small

#922 Beta release
  api/server/v1/header.go
  api/server/v1/marshaler.go
  query/filter/selector.go
  server/request/request.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  test/v1/server/auth_test.go
  test/v1/server/schema_test.go
Labels: large

#923 feat: Enabling full text search on database collection through schema
  query/filter/logical_test.go
  query/search/search_test.go
  query/update/operator_test.go
  schema/collection.go
  schema/collection_test.go
  schema/factory_builder.go
  schema/fields.go
  schema/fields_test.go
  schema/migration.go
  schema/queryable.go
  schema/rules.go
  schema/rules_test.go
  schema/schema.go
  schema/schema_test.go
  schema/search.go
  schema/search_test.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/quota/quota_test.go
  server/quota/storage_test.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/import_runner.go
  server/services/v1/database/mutator_test.go
  server/services/v1/database/query_runner_test.go
  server/services/v1/database/search_indexer_test.go
  server/services/v1/database/search_runner.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/search/runner.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
  test/v1/server/search_test.go
Labels: large

#925 chore: Adding more integration tests for field attributes
  schema/factory_builder.go
  schema/schema_test.go
  test/v1/server/collection_test.go
  test/v1/server/search_test.go
Labels: large

#924 feat: Add background queue api
  server/metadata/queue.go
  server/metadata/queue_test.go
  server/metadata/subscope_registry.go
Labels: large

#932 Equalize read and write unit size
  server/config/options.go
  server/quota/namespace_test.go
  server/quota/node_test.go
Labels: small, medium

#933 fix: looking up unknown namespace triggered an error
  server/request/request.go
Labels: small

#937 fix: Updated characters for client credentials
  server/services/v1/auth/gotrue.go
  test/v1/server/auth_test.go
Labels: small

#940 chore: Inspect generated id and secret's characters
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/gotrue_test.go
Labels: medium

#939 Auth caches refactor
  api/server/v1/header.go
  go.mod
  go.sum
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/services/v1/auth/gotrue.go
  server/services/v1/auth/gotrue_test.go
  server/services/v1/auth/provider.go
  test/docker/docker-compose.yml
  test/v1/server/auth_test.go
Labels: large

#941 fix: Detect incompatible schema changes in nested fields
  schema/rules.go
  schema/rules_test.go
Labels: medium

#942 refactor: Making store layer only transactional
  server/cdc/publisher.go
  server/main.go
  server/metadata/dictionary_test.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/metadata/version_test.go
  server/muxer/muxer.go
  server/quota/quota_test.go
  server/quota/storage_test.go
  server/services/v1/api.go
  server/services/v1/database/secondary_indexer_test.go
  server/services/v1/realtime.go
  server/services/v1/service.go
  server/transaction/manager.go
  store/kv/kv.go
  store/kv/kv_store.go
  store/kv/kv_test.go
  store/kv/measure.go
Labels: large

#943 fix: Check nested fields for backward compatibility check for search
  schema/rules.go
Labels: small

#935 feat: Implement chunker to split/merge the data to support bigger payloads
  internal/data.go
  internal/data.proto
  server/config/options.go
  server/services/v1/database/secondary_indexer.go
  server/transaction/manager.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  store/kv/fdb.go
  store/kv/kv_store.go
Labels: large

#946 fix: remove flaky queue test
  server/metadata/queue_test.go
Labels: small

#947 feat: Persist search indexes in foundationDB to have faster recovery in case of DR
  api/server/v1/header.go
  go.mod
  go.sum
  internal/data.go
  server/config/options.go
  server/main.go
  server/metadata/key_encoder.go
  server/metadata/tenant.go
  server/muxer/muxer.go
  server/request/request.go
  server/services/v1/database/query_runner.go
  server/services/v1/search.go
  server/services/v1/search/runner.go
  server/services/v1/service.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  store/kv/measure.go
  test/v1/server/document.go
  test/v1/server/search_test.go
Labels: large

#950 feat: remove unused kv interfaces
  server/metadata/tenant_test.go
  store/kv/base.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/kv_store.go
  store/kv/kv_test.go
  store/kv/measure.go
  store/kv/noop_store.go
Labels: medium, large

#952 Codecov config
  .codecov.yml
Labels: small

#953 chore: Add more request validation rules for search
  api/server/v1/search.go
  api/server/v1/validator.go
  test/v1/server/search_test.go
Labels: medium

#954 fix: Reload version in case of index not found
  api/server/v1/validator.go
  server/services/v1/search/errors.go
  server/services/v1/search/runner.go
  server/services/v1/search/session.go
  test/v1/server/search_test.go
Labels: medium

#955 Upgrade Go to 1.20.2
  go.mod
  scripts/install_go.sh
Labels: small

#949 feat: Support symmetric key token signature algorithm
  config/server.test.yaml
  docker/Dockerfile
  server/config/config.go
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/docker/test-token-hs.jwt
  test/docker/test-token-rsa.jwt
  test/v1/server/auth_test.go
Labels: large

#956 Upgrade deps
  go.mod
  go.sum
Labels: large

#958 fix: Fix unflatting object util method
  util/util.go
  util/util_test.go
Labels: small, medium

#959 fix: Handle negative floating point comparison
  value/value.go
  value/value_test.go
Labels: medium

#957 Allow persisting arrays with incomplete schema
  schema/factory_builder.go
  schema/fields.go
  schema/rules.go
  schema/schema_test.go
  test/v1/server/document_test.go
  util/util.go
Labels: medium, large

#960 Beta release
  .codecov.yml
  api/server/v1/search.go
  api/server/v1/validator.go
  config/server.test.yaml
  docker/Dockerfile
  go.mod
  go.sum
  schema/factory_builder.go
  schema/fields.go
  schema/rules.go
  schema/schema_test.go
  scripts/install_go.sh
  server/config/config.go
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/services/v1/search/errors.go
  server/services/v1/search/runner.go
  server/services/v1/search/session.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/docker/test-token-hs.jwt
  test/docker/test-token-rsa.jwt
  test/v1/server/auth_test.go
  test/v1/server/document_test.go
  test/v1/server/search_test.go
  util/util.go
  util/util_test.go
  value/value.go
  value/value_test.go
Labels: large

#961 fix: Move shared secret to Gotrue struct
  config/server.test.yaml
  server/config/options.go
  server/middleware/auth.go
  test/docker/docker-compose.yml
Labels: small

#962 Beta release
  config/server.test.yaml
  server/config/options.go
  server/middleware/auth.go
  test/docker/docker-compose.yml
Labels: small

#963 Allow maps in schema
  schema/collection.go
  schema/collection_test.go
  schema/fields.go
Labels: small, medium

#964 Fix typo
  README.md
Labels: small

#966 Update CLI tests
  .github/workflows/cli-test.yaml
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/main.sh
  test/v1/cli/scaffold.sh
  test/v1/cli/search/import.sh
Labels: large

#969 feat: Refactored Auth config to support multiple aud claims
  config/server.test.yaml
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/services/v1/auth/auth0.go
  server/services/v1/auth/gotrue.go
  test/docker/Dockerfile
  test/docker/test-token-A-hs.jwt
  test/docker/test-token-B-hs.jwt
  test/v1/server/auth_test.go
Labels: large

#968 feat: Support Accept header to stream application/json for read queries
  api/server/v1/header.go
  api/server/v1/marshaler.go
  server/request/request.go
  server/services/v1/database/query_runner.go
  test/v1/client/client_test.go
  test/v1/server/document_test.go
Labels: large

#971 Fix local image test workflow
  .github/workflows/test-docker-local-image.yaml
Labels: small

#970 Release Beta
  .github/workflows/cli-test.yaml
  .github/workflows/test-docker-local-image.yaml
  README.md
  api/server/v1/header.go
  api/server/v1/marshaler.go
  config/server.test.yaml
  schema/collection.go
  schema/collection_test.go
  schema/fields.go
  server/config/options.go
  server/middleware/auth.go
  server/middleware/auth_test.go
  server/request/request.go
  server/services/v1/auth/auth0.go
  server/services/v1/auth/gotrue.go
  server/services/v1/database/query_runner.go
  test/docker/Dockerfile
  test/docker/test-token-A-hs.jwt
  test/docker/test-token-B-hs.jwt
  test/v1/cli/backup.sh
  test/v1/cli/import.sh
  test/v1/cli/main.sh
  test/v1/cli/scaffold.sh
  test/v1/cli/search/import.sh
  test/v1/client/client_test.go
  test/v1/server/auth_test.go
  test/v1/server/document_test.go
Labels: large

#974 feat: Manage secondary indexes via metadata
  schema/collection.go
  schema/fields.go
  schema/rules.go
  schema/schema.go
  schema/schema_test.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/primary_index.go
  server/metadata/primary_index_test.go
  server/metadata/queue.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  store/search/search.go
Labels: large

#972 Allow object to map conversion
  schema/fields.go
  schema/rules.go
  schema/rules_test.go
Labels: medium, large

#965 refactor: Move listener out of FDB and move it at the top of chain
  server/main.go
  server/muxer/muxer.go
  server/services/v1/database/search_indexer.go
  server/services/v1/service.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/listener.go
  store/kv/listener_store.go
  store/kv/measure.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
Labels: large

#980 Update README
  README.md
Labels: small

#978 chore: Code improvements on collection metadata
  schema/fields.go
  server/metadata/collection.go
Labels: medium

#945 feat: report usage based metrics
  server/config/options.go
  server/main.go
  server/metadata/namespace.go
  server/metrics/global_status.go
  server/metrics/global_status_test.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/requests.go
  server/metrics/units.go
  server/metrics/units_test.go
  server/middleware/measure.go
  server/services/v1/billing/metronome.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/measure.go
  server/services/v1/database/measure_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/row_reader.go
  server/services/v1/database/secondary_indexer.go
  store/kv/fdb.go
  store/kv/kv_store.go
  store/kv/listener.go
  store/kv/measure.go
Labels: large

#985 Beta release
  README.md
  go.mod
  go.sum
  schema/collection.go
  schema/factory_builder.go
  schema/fields.go
  schema/rules.go
  schema/rules_test.go
  schema/schema.go
  schema/schema_test.go
  server/config/options.go
  server/main.go
  server/metadata/collection.go
  server/metadata/collection_test.go
  server/metadata/dictionary.go
  server/metadata/dictionary_test.go
  server/metadata/namespace.go
  server/metadata/primary_index.go
  server/metadata/primary_index_test.go
  server/metadata/queue.go
  server/metadata/tenant.go
  server/metadata/tenant_test.go
  server/metrics/global_status.go
  server/metrics/global_status_test.go
  server/metrics/measurement.go
  server/metrics/metrics.go
  server/metrics/requests.go
  server/metrics/units.go
  server/metrics/units_test.go
  server/middleware/measure.go
  server/muxer/muxer.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/billing/noop.go
  server/services/v1/billing/provider.go
  server/services/v1/billing/provider_test.go
  server/services/v1/database/base_runner.go
  server/services/v1/database/collection_runner.go
  server/services/v1/database/database_runner.go
  server/services/v1/database/measure.go
  server/services/v1/database/measure_test.go
  server/services/v1/database/query_runner.go
  server/services/v1/database/row_reader.go
  server/services/v1/database/search_indexer.go
  server/services/v1/database/search_reader.go
  server/services/v1/database/secondary_index_reader.go
  server/services/v1/database/secondary_indexer.go
  server/services/v1/management.go
  server/services/v1/service.go
  store/kv/chunk.go
  store/kv/chunk_test.go
  store/kv/fdb.go
  store/kv/kv.go
  store/kv/kv_store.go
  store/kv/listener.go
  store/kv/listener_store.go
  store/kv/measure.go
  store/search/search.go
  test/v1/server/document_test.go
  test/v1/server/integration_test.go
Labels: large

#986 Retry on search schema update race
  server/services/v1/database/sessions.go
  store/search/errors.go
Labels: small

#982 [WIP] fix: Using search backend for OR queries
  query/filter/filter.go
  query/filter/logical.go
  query/filter/logical_test.go
  query/filter/selector.go
  query/search/search_test.go
  server/search/facets.go
  server/search/facets_test.go
  server/search/factory.go
  server/search/hits.go
  server/search/hits_test.go
  server/search/sorted_hits.go
  server/search/sorted_hits_test.go
  server/services/v1/database/search_reader.go
  server/services/v1/search/reader.go
  store/search/ts.go
Labels: large

#987 Improve tests
  .github/workflows/go-test.yaml
  Makefile
  api/server/v1/marshaler.go
  api/server/v1/marshaler_test.go
  config/server.test.yaml
  server/metadata/metadata.go
  server/services/v1/user_metadata_provider.go
  store/search/errors.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/v1/server/auth_test.go
  test/v1/server/integration_test.go
  test/v1/server/management_test.go
Labels: large

#990 fix: Billing start date to be the same day at 00:00 UTC
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
Labels: small

#991 TigrisError tests added
  api/server/v1/error.go
  api/server/v1/error_test.go
  query/filter/logical.go
  query/filter/logical_test.go
  server/search/facets.go
  server/search/facets_test.go
  server/services/v1/search/reader.go
Labels: large

#992 Beta release
  .github/workflows/go-test.yaml
  Makefile
  api/server/v1/error.go
  api/server/v1/error_test.go
  api/server/v1/marshaler.go
  api/server/v1/marshaler_test.go
  config/server.test.yaml
  query/filter/filter.go
  query/filter/logical.go
  query/filter/logical_test.go
  query/filter/selector.go
  query/search/search_test.go
  server/metadata/metadata.go
  server/search/facets.go
  server/search/facets_test.go
  server/search/factory.go
  server/search/hits.go
  server/search/hits_test.go
  server/search/sorted_hits.go
  server/search/sorted_hits_test.go
  server/services/v1/billing/metronome.go
  server/services/v1/billing/metronome_test.go
  server/services/v1/database/search_reader.go
  server/services/v1/database/sessions.go
  server/services/v1/search/reader.go
  server/services/v1/user_metadata_provider.go
  store/search/errors.go
  store/search/ts.go
  test/docker/Dockerfile
  test/docker/docker-compose.yml
  test/v1/server/auth_test.go
  test/v1/server/integration_test.go
  test/v1/server/management_test.go
Labels: large
